CREATE DATABASE Brawon_Heath;
GO

USE Brawon_Heath;
GO

CREATE TABLE PRESCRIPTIONS
(
    PRESCRIPTION_ID INT PRIMARY KEY,
    [DATE] DATE,
    QUANTITY INT
);
GO

CREATE TABLE DOCTORS
(
    ID INT PRIMARY KEY,
    DOC_NAME VARCHAR(100),
    DOC_EMAIL VARCHAR(100),
    DOC_PHONE_NUMBER VARCHAR(20),
    EXPERIENCE_YEARS INT,
    SPECIALITY VARCHAR(100),
    PRESCRIPTION_ID INT,
    FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTIONS(PRESCRIPTION_ID)
);
GO

CREATE TABLE Pharmaceuical_Companies
(
    COMP_NAME VARCHAR(100) PRIMARY KEY,
    COMP_PHONE_NUMBER VARCHAR(20),
    COMP_ADRESSES VARCHAR(200)
);
GO

CREATE TABLE DRUGS
(
    DRUG_ID INT PRIMARY KEY IDENTITY(1,1), 
    TRADE_NAME VARCHAR(100),
    DRUG_STRENGTH VARCHAR(50),
    COMP_NAME VARCHAR(100),
    FOREIGN KEY (COMP_NAME) REFERENCES Pharmaceuical_Companies(COMP_NAME)
);
GO

CREATE TABLE PATIENTS
(
    UR_NUMBER INT PRIMARY KEY,
    ADDRESSES VARCHAR(200),
    NAME VARCHAR(100),
    AGE INT,
    PHONE_NUMBER VARCHAR(20),
    MEDICARE_CARD_NUMBER BIGINT, 
    ID INT,
    PRESCRIPTION_ID INT,
    FOREIGN KEY (ID) REFERENCES DOCTORS(ID),
    FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTIONS(PRESCRIPTION_ID)
);

