CREATE DATABASE Brawon_Heath;
GO

USE Brawon_Heath;
GO

CREATE TABLE PRESCRIPTIONS
(
    PRESCRIPTION_ID INT PRIMARY KEY,
    [DATE] DATE,
    QUANTITY INT
);
GO

CREATE TABLE DOCTORS
(
    ID INT PRIMARY KEY,
    DOC_NAME VARCHAR(50),
    DOC_EMAIL VARCHAR(50),
    DOC_PHONE_NUMBER VARCHAR(50),
    EXPERIENCE_YEARS INT,
    SPECIALITY VARCHAR(50),
    PRESCRIPTION_ID INT,
    FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTIONS(PRESCRIPTION_ID)
);
CREATE TABLE PATIENTS
(
UR_NUMBER INT PRIMARY KEY,
ADDRESSES VARCHAR,
NAME VARCHAR,
AGE INT,
PHONE_NUMBER VARCHAR,
MEDICARE_CARD_NUMBER INT,
ID INT,
    FOREIGN KEY (ID) REFERENCES DOCTORS (ID),

PRESCRIPTION_ID INT,
    FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTIONS(PRESCRIPTION_ID)

);
CREATE TABLE Pharmaceuical_Companies
(
COMP_NAME VARCHAR PRIMARY KEY ,
COMP_PHONE_NUMBER VARCHAR,
COMP_ADRESSES VARCHAR
);

CREATE TABLE DRUGS
(
TRADE_NAME VARCHAR,
DRUG_STRENGTH VARCHAR(50),
COMP_NAME VARCHAR ,
FOREIGN KEY (COMP_NAME) REFERENCES Pharmaceuical_Companies    (COMP_NAME )

);


